name: flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.6.2
  firebase_database: 11.3.10
  firebase_storage: ^12.1.0
  image_picker: ^1.1.1

  # Charts
  fl_chart: ^0.69.0

  http: ^1.2.2
  dropdown_search: ^5.0.6

  google_sign_in: ^6.2.1
  image_cropper: ^11.0.0
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/avatars/
