// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4T0nSG3xmpyNvd4NhYGNx1UkzQNP9zWo',
    appId: '1:576400581098:web:12fbd30ce003ceea34d293',
    messagingSenderId: '576400581098',
    projectId: 'rmutl-fullproject',
    authDomain: 'rmutl-fullproject.firebaseapp.com',
    storageBucket: 'rmutl-fullproject.firebasestorage.app',
    measurementId: 'G-ZTW770HRL3',
    databaseURL:
        'https://rmutl-fullproject-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhD_jHIdwNIqvK1RItd_fCWjtXNGlM24A',
    appId: '1:576400581098:android:ccad7bd5ffe2c58234d293',
    messagingSenderId: '576400581098',
    projectId: 'rmutl-fullproject',
    storageBucket: 'rmutl-fullproject.firebasestorage.app',
    databaseURL:
        'https://rmutl-fullproject-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3TtpLrzAY8pOTZGrtK6_KUSmXvTFDTI',
    appId: '1:576400581098:ios:e69d3ea01353e63334d293',
    messagingSenderId: '576400581098',
    projectId: 'rmutl-fullproject',
    storageBucket: 'rmutl-fullproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
    databaseURL:
        'https://rmutl-fullproject-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK3TtpLrzAY8pOTZGrtK6_KUSmXvTFDTI',
    appId: '1:576400581098:ios:e69d3ea01353e63334d293',
    messagingSenderId: '576400581098',
    projectId: 'rmutl-fullproject',
    storageBucket: 'rmutl-fullproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
    databaseURL:
        'https://rmutl-fullproject-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4T0nSG3xmpyNvd4NhYGNx1UkzQNP9zWo',
    appId: '1:576400581098:web:aa5dd6fa12bc5ced34d293',
    messagingSenderId: '576400581098',
    projectId: 'rmutl-fullproject',
    authDomain: 'rmutl-fullproject.firebaseapp.com',
    storageBucket: 'rmutl-fullproject.firebasestorage.app',
    measurementId: 'G-D6KJLX53P4',
    databaseURL:
        'https://rmutl-fullproject-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}